### ISSUE TITLE
How to use struct Person in java?

### ISSUE THREAD

**Issue by huanxue318** [bytedeco/helloworld#1]
Hi

I found the following codes in helloworld.h but I did not find any examples using them in Java,any instructions？what I aim to is to map C++ struct  to java and use them

 // by value
 struct Person getPerson();
 void printPerson (struct Person p);

**Comment by saudet** [comment]
If you add a `struct` to helloworld.h, it will do the rest automatically.

**Comment by matteodg** [comment]
Hello, sorry for the late reply: that example is only in the master branch of bytedeco/helloworld repository and the Java counterpart is not yet committed in the bytedeco/javacpp-presets repository in the helloworld branch. Unfortunately right now I can access to my local repo with those changes, I'll work in the next days to make it available!

**Comment by matteodg** [comment]
I just created a PR https://github.com/bytedeco/javacpp-presets/pull/779 with the helloworld 2.0 that includes an example with a struct.

**Comment by saudet** [comment]
@matteodg Merged. Thanks for the update!
